name: Reviewdog
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20.15.1"

      - name: Install required dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint src/ | tee eslint-output.txt
        continue-on-error: true

      - name: Reviewdog
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: diff_context
          fail_on_error: false
          level: warning
          eslint_flags: "src/ --format=unix"
          input: eslint-output.txt
